volumes:
  postgres-db:

services:
  node-server:
    container_name: node-server
    build:
      context: ./server
    env_file:
      - ./server/.env
    ports:
      - 3000:3000
    depends_on:
      - db
    volumes:
      - type: bind
        source: ./server/src
        target: /home/node/app/src
    command: npm run start:dev

  db:
    container_name: db
    image: postgres:17-alpine
    restart: always
    shm_size: 128mb
    env_file:
      - ./server/.env
    volumes:
      - postgres-db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    user: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres"]
      interval: 30s
      timeout: 10s
      retries: 5

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080

  # frontend:
  #   container_name: frontend
  #   build:
  #     context: ./client
  #   ports:
  #     - 5173:5173
  #   volumes:
  #     - ./frontend:/app
  #     - /app/node_modules
  #   command: npm run dev
  #   depends_on:
  #     - node-server
