export enum QuestCategory {
  ADVENTURE = 'adventure',
  HORROR = 'horror',
  MYSTERY = 'mystery',
  SCI_FI = 'sci-fi',
  FANTASY = 'fantasy',
  HISTORICAL = 'historical',
  DETECTIVE = 'detective',
  SURVIVAL = 'survival',
  ESCAPE_ROOM = 'escape-room',
  POST_APOCALYPTIC = 'post-apocalyptic',
  STEAMPUNK = 'steampunk',
  CYBERPUNK = 'cyberpunk',
  SUPERNATURAL = 'supernatural',
  THRILLER = 'thriller',
  WESTERN = 'western',
  MEDIEVAL = 'medieval',
  SPACE = 'space',
  PIRATE = 'pirate',
  COMEDY = 'comedy',
  WAR = 'war',
}
