export enum REPOSITORY {
  USER = "USER_REPOSITORY",
  QUEST = "QUEST_REPOSITORY",
  RATING = "RATING_REPOSITORY",
  TASK = "TASK_REPOSITORY",
  ANSWER = "ANSWER_REPOSITORY",
  PROGRESS = "PROGRESS_REPOSITORY",
}
